apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscompanyservice 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dmscompanyservice
  template:
    metadata:
      labels:
        app: dmscompanyservice 
    spec:
      containers:
        - name: dmscompanyservice 
          image: dmsacr.azurecr.io/dmscompanyservice
          ports:
          - containerPort: 80