apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscompanyserviceprod 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmscompanyserviceprod
  template:
    metadata:
      labels:
        app: dmscompanyserviceprod 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscompanyserviceprod 
          image: microservicesacrafrprd.azurecr.io/dmscompanyserviceprod
          ports:
          - containerPort: 80