apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscompanyserviceqa 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmscompanyserviceqa
  template:
    metadata:
      labels:
        app: dmscompanyserviceqa 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscompanyserviceqa 
          image: microservicesacrafrqa.azurecr.io/dmscompanyserviceqa
          ports:
          - containerPort: 80