apiVersion : apps/v1
kind: Deployment
metadata:
  name: dmscompanyservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmscompanyservice
  template:
    metadata:
      labels:
        app: dmscompanyservice 
    spec:
      nodeSelector:
        "kubernetes.io/os": linux      
      containers:
        - name: dmscompanyservice 
          image: microservicesacrafrdev.azurecr.io/dmscompanyservice:latest
          ports:
          - containerPort: 80